"use client";
import { crearEmpresasRequest } from "@/api/EmpresasApi";
import {
  Button,
  Container,
  FormControl,
  Grid,
  MenuItem,
  Paper,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import { useSnackbar } from "notistack";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";

const Crear = () => {
  const colombia = [
    {
      departamento: "AMAZONAS",
      municipios: [
        "EL ENCANTO",
        "LA CHORRERA",
        "LA PEDRERA",
        "LA VICTORIA",
        "LETICIA",
        "MIRITI - PARANÁ",
        "PUERTO ALEGRIA",
        "PUERTO ARICA",
        "PUERTO NARIÑO",
        "PUERTO SANTANDER",
        "TARAPACÁ",
      ],
    },
    {
      departamento: "ANTIOQUIA",
      municipios: [
        "CÁCERES",
        "CAUCASIA",
        "EL BAGRE",
        "NECHÍ",
        "TARAZÁ",
        "ZARAGOZA",
        "CARACOLÍ",
        "MACEO",
        "PUERTO BERRiO",
        "PUERTO NARE",
        "PUERTO TRIUNFO",
        "YONDÓ",
        "AMALFI",
        "ANORÍ",
        "CISNEROS",
        "REMEDIOS",
        "SAN ROQUE",
        "SANTO DOMINGO",
        "SEGOVIA",
        "VEGACHÍ",
        "YALÍ",
        "YOLOMBÓ",
        "ANGOSTURA",
        "BELMIRA",
        "BRICEÑO",
        "CAMPAMENTO",
        "CAROLINA",
        "DON MATiAS",
        "ENTRERRIOS",
        "GÓMEZ PLATA",
        "GUADALUPE",
        "ITUANGO",
        "SAN ANDRÉS",
        "SAN JOSÉ DE LA MONTAÑA",
        "SAN PEDRO",
        "SANTA ROSA de osos",
        "TOLEDO",
        "VALDIVIA",
        "YARUMAL",
        "ABRIAQUÍ",
        "ANZA",
        "ARMENIA",
        "BURITICÁ",
        "CAÑASGORDAS",
        "DABEIBA",
        "EBÉJICO",
        "FRONTINO",
        "GIRALDO",
        "HELICONIA",
        "LIBORINA",
        "OLAYA",
        "PEQUE",
        "SABANALARGA",
        "SAN JERÓNIMO",
        "SANTAFÉ DE ANTIOQUIA",
        "SOPETRaN",
        "URAMITA",
        "ABEJORRAL",
        "ALEJANDRÍA",
        "ARGELIA",
        "CARMEN DE VIBORAL",
        "COCORNÁ",
        "CONCEPCIÓN",
        "GRANADA",
        "GUARNE",
        "GUATAPE",
        "LA CEJA",
        "LA UNIÓN",
        "MARINILLA",
        "NARIÑO",
        "PEÑOL",
        "RETIRO",
        "RIONEGRO",
        "SAN CARLOS",
        "SAN FRANCISCO",
        "SAN LUIS",
        "SAN RAFAEL",
        "SAN VICENTE",
        "SANTUARIO",
        "SONSON",
        "AMAGA",
        "ANDES",
        "ANGELOPOLIS",
        "BETANIA",
        "BETULIA",
        "CAICEDO",
        "CARAMANTA",
        "CIUDAD BOLÍVAR",
        "CONCORDIA",
        "FREDONIA",
        "HISPANIA",
        "JARDÍN",
        "JERICÓ",
        "LA PINTADA",
        "MONTEBELLO",
        "PUEBLORRICO",
        "SALGAR",
        "SANTA BaRBARA",
        "TÁMESIS",
        "TARSO",
        "TITIRIBÍ",
        "URRAO",
        "VALPARAISO",
        "VENECIA",
        "APARTADÓ",
        "ARBOLETES",
        "CAREPA",
        "CHIGORODÓ",
        "MURINDÓ",
        "MUTATA",
        "NECOCLÍ",
        "SAN JUAN DE URABA",
        "SAN PEDRO DE URABA",
        "TURBO",
        "VIGÍA DEL FUERTE",
        "BARBOSA",
        "BELLO",
        "CALDAS",
        "COPACABANA",
        "ENVIGADO",
        "GIRARDOTA",
        "ITAGUI",
        "LA ESTRELLA",
        "MEDELLÍN",
        "SABANETA",
      ],
    },
    {
      departamento: "ARAUCA",
      municipios: [
        "ARAUCA",
        "ARAUQUITA",
        "CRAVO NORTE",
        "FORTUL",
        "PUERTO RONDÓN",
        "SARAVENA",
        "TAME",
      ],
    },
    {
      departamento: "ARCHIPIELAGO DE SAN ANDRES",
      municipios: ["PROVIDENCIA Y SANTA CATALINA", "SAN ANDReS"],
    },
    {
      departamento: "ATLÁNTICO",
      municipios: [
        "BARRANQUILLA",
        "GALAPA",
        "MALAMBO",
        "PUERTO COLOMBIA",
        "SOLEDAD",
        "CAMPO DE LA CRUZ",
        "CANDELARIA",
        "LURUACO",
        "MANATi",
        "REPELON",
        "SANTA LUCiA",
        "SUAN",
        "BARANOA",
        "PALMAR DE VARELA",
        "POLONUEVO",
        "PONEDERA",
        "Sabanagrande",
        "SABANALARGA",
        "Santo Tomas",
        "JUAN DE ACOSTA",
        "PIOJÓ",
        "TUBARA",
        "USIACURi",
      ],
    },
    {
      departamento: "BOGOTÁ D.C.",
      municipios: ["BOGOTA D.C."],
    },
    {
      departamento: "BOLIVAR",
      municipios: [
        "CICUCO",
        "HATILLO DE LOBA",
        "MARGARITA",
        "MOMPÓS",
        "SAN FERNANDO",
        "TALAIGUA NUEVO",
        "ARJONA",
        "ARROYOHONDO",
        "CALAMAR",
        "CARTAGENA",
        "CLEMENCIA",
        "MAHATES",
        "SAN CRISTOBAL",
        "SAN ESTANISLAO",
        "SANTA CATALINA",
        "SANTA ROSA DE LIMA",
        "SOPLAVIENTO",
        "TURBACO",
        "TURBANA",
        "VILLANUEVA",
        "ALTOS DEL ROSARIO",
        "BARRANCO DE LOBA",
        "EL PEÑON",
        "REGIDOR",
        "RÍO VIEJO",
        "SAN MARTIN DE LOBA",
        "ARENAL",
        "CANTAGALLO",
        "MORALES",
        "SAN PABLO",
        "SANTA ROSA DEL SUR",
        "SIMITÍ",
        "ACHÍ",
        "MAGANGUÉ",
        "MONTECRISTO",
        "PINILLOS",
        "SAN JACINTO DEL CAUCA",
        "TIQUISIO",
        "CARMEN DE BOLÍVAR",
        "CÓRDOBA",
        "EL GUAMO",
        "MARÍA LA BAJA",
        "SAN JACINTO",
        "SAN JUAN NEPOMUCENO",
        "ZAMBRANO",
      ],
    },
    {
      departamento: "BOYACÁ",
      municipios: [
        "CHÍQUIZA",
        "CHIVATÁ",
        "CÓMBITA",
        "CUCAITA",
        "MOTAVITA",
        "OICATÁ",
        "SAMACÁ",
        "SIACHOQUE",
        "SORA",
        "SORACÁ",
        "SOTAQUIRÁ",
        "TOCA",
        "TUNJA",
        "TUTA",
        "VENTAQUEMADA",
        "CHISCAS",
        "CUBARÁ",
        "EL COCUY",
        "EL ESPINO",
        "GUACAMAYAS",
        "GÜICÁN",
        "PANQUEBA",
        "LABRANZAGRANDE",
        "PAJARITO",
        "PAYA",
        "PISBA",
        "BERBEO",
        "CAMPOHERMOSO",
        "MIRAFLORES",
        "PÁEZ",
        "SAN EDUARDO",
        "ZETAQUIRA",
        "BOYACÁ",
        "CIÉNEGA",
        "JENESANO",
        "NUEVO COLÓN",
        "RAMIRIQUÍ",
        "RONDÓN",
        "TIBANÁ",
        "TURMEQUÉ",
        "UMBITA",
        "VIRACACHÁ",
        "CHINAVITA",
        "GARAGOA",
        "MACANAL",
        "PACHAVITA",
        "SAN LUIS DE GACENO",
        "SANTA MARÍA",
        "BOAVITA",
        "COVARACHÍA",
        "LA UVITA",
        "SAN MATEO",
        "SATIVANORTE",
        "SATIVASUR",
        "SOATÁ",
        "SUSACÓN",
        "TIPACOQUE",
        "BRICEÑO",
        "BUENAVISTA",
        "CALDAS",
        "CHIQUINQUIRÁ",
        "COPER",
        "LA VICTORIA",
        "MARIPÍ",
        "MUZO",
        "OTANCHE",
        "PAUNA",
        "PUERTO BOYACa",
        "QUÍPAMA",
        "SABOYÁ",
        "SAN MIGUEL DE SEMA",
        "SAN PABLO BORBUR",
        "TUNUNGUÁ",
        "ALMEIDA",
        "CHIVOR",
        "GUATEQUE",
        "GUAYATÁ",
        "LA CAPILLA",
        "SOMONDOCO",
        "SUTATENZA",
        "TENZA",
        "ARCABUCO",
        "CHITARAQUE",
        "GACHANTIVÁ",
        "MONIQUIRÁ",
        "RÁQUIRA",
        "SÁCHICA",
        "SAN JOSÉ DE PARE",
        "SANTA SOFÍA",
        "SANTANA",
        "SUTAMARCHÁN",
        "TINJACÁ",
        "TOGÜÍ",
        "VILLA DE LEYVA",
        "AQUITANIA",
        "CUÍTIVA",
        "FIRAVITOBA",
        "GAMEZA",
        "IZA",
        "MONGUA",
        "MONGUÍ",
        "NOBSA",
        "PESCA",
        "SOGAMOSO",
        "TIBASOSA",
        "TÓPAGA",
        "TOTA",
        "BELÉN",
        "BUSBANZÁ",
        "CERINZA",
        "CORRALES",
        "DUITAMA",
        "FLORESTA",
        "PAIPA",
        "SAN ROSA VITERBO",
        "TUTAZÁ",
        "BETÉITIVA",
        "CHITA",
        "JERICÓ",
        "PAZ DE RÍO",
        "SOCHA",
        "SOCOTÁ",
        "TASCO",
      ],
    },
    {
      departamento: "CALDAS",
      municipios: [
        "FILADELFIA",
        "LA MERCED",
        "MARMATO",
        "RIOSUCIO",
        "SUPÍA",
        "MANZANARES",
        "MARQUETALIA",
        "MARULANDA",
        "PENSILVANIA",
        "ANSERMA",
        "BELALCÁZAR",
        "RISARALDA",
        "SAN JOSÉ",
        "VITERBO",
        "CHINCHINa",
        "MANIZALES",
        "NEIRA",
        "PALESTINA",
        "VILLAMARiA",
        "AGUADAS",
        "ARANZAZU",
        "PÁCORA",
        "SALAMINA",
        "LA DORADA",
        "NORCASIA",
        "SAMANÁ",
        "VICTORIA",
      ],
    },
    {
      departamento: "CAQUETA",
      municipios: [
        "ALBANIA",
        "BELÉN DE LOS ANDAQUIES",
        "CARTAGENA DEL CHAIRÁ",
        "CURRILLO",
        "EL DONCELLO",
        "EL PAUJIL",
        "FLORENCIA",
        "LA MONTAÑITA",
        "MILaN",
        "MORELIA",
        "PUERTO RICO",
        "SAN JOSE DEL FRAGUA",
        "SAN VICENTE DEL CAGUÁN",
        "SOLANO",
        "SOLITA",
        "VALPARAISO",
      ],
    },
    {
      departamento: "CASANARE",
      municipios: [
        "AGUAZUL",
        "CHAMEZA",
        "HATO COROZAL",
        "LA SALINA",
        "MANÍ",
        "MONTERREY",
        "NUNCHÍA",
        "OROCUÉ",
        "PAZ DE ARIPORO",
        "PORE",
        "RECETOR",
        "SABANALARGA",
        "SÁCAMA",
        "SAN LUIS DE PALENQUE",
        "TÁMARA",
        "TAURAMENA",
        "TRINIDAD",
        "VILLANUEVA",
        "YOPAL",
      ],
    },
    {
      departamento: "CAUCA",
      municipios: [
        "CAJIBÍO",
        "EL TAMBO",
        "LA SIERRA",
        "MORALES",
        "PIENDAMO",
        "POPAYÁN",
        "ROSAS",
        "SOTARA",
        "TIMBIO",
        "BUENOS AIRES",
        "CALOTO",
        "CORINTO",
        "MIRANDA",
        "PADILLA",
        "PUERTO TEJADA",
        "SANTANDER DE QUILICHAO",
        "SUAREZ",
        "VILLA RICA",
        "GUAPI",
        "LOPEZ",
        "TIMBIQUI",
        "CALDONO",
        "INZÁ",
        "JAMBALO",
        "PAEZ",
        "PURACE",
        "Silvia",
        "TORIBIO",
        "TOTORO",
        "ALMAGUER",
        "ARGELIA",
        "BALBOA",
        "BOLÍVAR",
        "FLORENCIA",
        "LA VEGA",
        "MERCADERES",
        "PATIA",
        "PIAMONTE",
        "SAN SEBASTIAN",
        "SANTA ROSA",
        "SUCRE",
      ],
    },
    {
      departamento: "CESAR",
      municipios: [
        "BECERRIL",
        "CHIMICHAGUA",
        "CHIRIGUANA",
        "CURUMANÍ",
        "LA JAGUA DE IBIRICO",
        "PAILITAS",
        "TAMALAMEQUE",
        "ASTREA",
        "BOSCONIA",
        "EL COPEY",
        "EL PASO",
        "AGUSTÍN CODAZZI",
        "LA PAZ",
        "MANAURE",
        "PUEBLO BELLO",
        "SAN DIEGO",
        "VALLEDUPAR",
        "AGUACHICA",
        "GAMARRA",
        "GONZÁLEZ",
        "LA GLORIA",
        "PELAYA",
        "RÍO DE ORO",
        "SAN ALBERTO",
        "SAN MARTÍN",
      ],
    },
    {
      departamento: "CHOCO",
      municipios: [
        "ATRATO",
        "BAGADÓ",
        "BOJAYA",
        "EL CARMEN DE ATRATO",
        "LLORÓ",
        "MEDIO ATRATO",
        "QUIBDÓ",
        "RIO QUITO",
        "ACANDÍ",
        "BELÉN DE BAJIRA",
        "CARMÉN DEL DARIÉN",
        "RIOSUCIO",
        "UNGUÍA",
        "BAHÍA SOLANO",
        "JURADÓ",
        "NUQUÍ",
        "ALTO BAUDÓ",
        "BAJO BAUDÓ",
        "El Litoral del San Juan",
        "MEDIO BAUDÓ",
        "CANTON DE SAN PABLO",
        "CERTEGUI",
        "CONDOTO",
        "ITSMINA",
        "MEDIO SAN JUAN",
        "NÓVITA",
        "RÍO FRÍO",
        "SAN JOSÉ DEL PALMAR",
        "SIPÍ",
        "TADÓ",
        "UNION PANAMERICANA",
      ],
    },
    {
      departamento: "CORDOBA",
      municipios: [
        "TIERRALTA",
        "VALENCIA",
        "CHIMÁ",
        "COTORRA",
        "LORICA",
        "MOMIL",
        "PURÍSIMA",
        "MONTERÍA",
        "CANALETE",
        "LOS CÓRDOBAS",
        "MOÑITOS",
        "PUERTO ESCONDIDO",
        "SAN ANTERO",
        "SAN BERNARDO DEL VIENTO",
        "CHINÚ",
        "SAHAGÚN",
        "SAN ANDRÉS SOTAVENTO",
        "AYAPEL",
        "BUENAVISTA",
        "LA APARTADA",
        "MONTELÍBANO",
        "PLANETA RICA",
        "PUEBLO NUEVO",
        "PUERTO LIBERTADOR",
        "CERETÉ",
        "CIÉNAGA DE ORO",
        "SAN CARLOS",
        "SAN PELAYO",
      ],
    },
    {
      departamento: "CUNDINAMARCA",
      municipios: [
        "CHOCONTÁ",
        "MACHETA",
        "MANTA",
        "SESQUILÉ",
        "SUESCA",
        "TIBIRITA",
        "VILLAPINZÓN",
        "AGUA DE DIOS",
        "GIRARDOT",
        "GUATAQUÍ",
        "JERUSALÉN",
        "NARIÑO",
        "NILO",
        "RICAURTE",
        "TOCAIMA",
        "CAPARRAPÍ",
        "GUADUAS",
        "PUERTO SALGAR",
        "ALBÁN",
        "LA PEÑA",
        "LA VEGA",
        "NIMAIMA",
        "NOCAIMA",
        "QUEBRADANEGRA",
        "SAN FRANCISCO",
        "SASAIMA",
        "SUPATÁ",
        "ÚTICA",
        "VERGARA",
        "VILLETA",
        "GACHALA",
        "GACHETA",
        "GAMA",
        "GUASCA",
        "GUATAVITA",
        "JUNÍN",
        "LA CALERA",
        "UBALÁ",
        "BELTRÁN",
        "BITUIMA",
        "CHAGUANÍ",
        "GUAYABAL DE SIQUIMA",
        "PULI",
        "SAN JUAN DE RÍO SECO",
        "VIANÍ",
        "MEDINA",
        "PARATEBUENO",
        "CAQUEZA",
        "CHIPAQUE",
        "CHOACHÍ",
        "FOMEQUE",
        "FOSCA",
        "GUAYABETAL",
        "GUTIÉRREZ",
        "QUETAME",
        "UBAQUE",
        "UNE",
        "EL PEÑÓN",
        "LA PALMA",
        "PACHO",
        "PAIME",
        "SAN CAYETANO",
        "TOPAIPI",
        "VILLAGOMEZ",
        "YACOPÍ",
        "CAJICÁ",
        "CHÍA",
        "COGUA",
        "GACHANCIPÁ",
        "NEMOCoN",
        "SOPÓ",
        "TABIO",
        "TOCANCIPÁ",
        "ZIPAQUIRÁ",
        "BOJACÁ",
        "COTA",
        "EL ROSAL",
        "FACATATIVÁ",
        "FUNZA",
        "MADRID",
        "MOSQUERA",
        "SUBACHOQUE",
        "TENJO",
        "ZIPACoN",
        "SIBATÉ",
        "SOACHA",
        "ARBELÁEZ",
        "CABRERA",
        "FUSAGASUGÁ",
        "GRANADA",
        "PANDI",
        "PASCA",
        "SAN BERNARDO",
        "SILVANIA",
        "TIBACUY",
        "VENECIA",
        "ANAPOIMA",
        "ANOLAIMA",
        "APULO",
        "CACHIPAY",
        "EL COLEGIO",
        "LA MESA",
        "QUIPILE",
        "SAN ANTONIO DE TEQUENDAMA",
        "TENA",
        "VIOTÁ",
        "CARMEN DE CARUPA",
        "CUCUNUBÁ",
        "FÚQUENE",
        "GUACHETÁ",
        "LENGUAZAQUE",
        "SIMIJACA",
        "SUSA",
        "SUTATAUSA",
        "TAUSA",
        "UBATE",
      ],
    },
    {
      departamento: "GUAINIA",
      municipios: [
        "BARRANCO MINA",
        "CACAHUAL",
        "INÍRIDA",
        "LA GUADALUPE",
        "MAPIRIPaN",
        "MORICHAL",
        "PANA PANA",
        "PUERTO COLOMBIA",
        "SAN FELIPE",
      ],
    },
    {
      departamento: "GUAVIARE",
      municipios: [
        "CALAMAR",
        "EL RETORNO",
        "MIRAFLORES",
        "SAN JOSÉ DEL GUAVIARE",
      ],
    },
    {
      departamento: "HUILA",
      municipios: [
        "AGRADO",
        "ALTAMIRA",
        "GARZÓN",
        "GIGANTE",
        "GUADALUPE",
        "PITAL",
        "SUAZA",
        "TARQUI",
        "AIPE",
        "ALGECIRAS",
        "BARAYA",
        "CAMPOALEGRE",
        "COLOMBIA",
        "HOBO",
        "IQUIRA",
        "NEIVA",
        "PALERMO",
        "RIVERA",
        "SANTA MARÍA",
        "TELLO",
        "TERUEL",
        "VILLAVIEJA",
        "YAGUARÁ",
        "LA ARGENTINA",
        "LA PLATA",
        "NÁTAGA",
        "PAICOL",
        "TESALIA",
        "ACEVEDO",
        "ELÍAS",
        "ISNOS",
        "OPORAPA",
        "PALESTINA",
        "PITALITO",
        "SALADOBLANCO",
        "SAN AGUSTÍN",
        "TIMANÁ",
      ],
    },
    {
      departamento: "LA GUAJIRA",
      municipios: [
        "ALBANIA",
        "DIBULLA",
        "MAICAO",
        "MANAURE",
        "RIOHACHA",
        "URIBIA",
        "BARRANCAS",
        "DISTRACCION",
        "EL MOLINO",
        "FONSECA",
        "HATONUEVO",
        "LA JAGUA DEL PILAR",
        "SAN JUAN DEL CESAR",
        "URUMITA",
        "VILLANUEVA",
      ],
    },
    {
      departamento: "MAGDALENA",
      municipios: [
        "ARIGUANÍ",
        "CHIBOLO",
        "NUEVA GRANADA",
        "PLATO",
        "SABANAS DE SAN ANGEL",
        "TENERIFE",
        "ALGARROBO",
        "ARACATACA",
        "CIÉNAGA",
        "EL RETEN",
        "FUNDACION",
        "PUEBLO VIEJO",
        "ZONA BANANERA",
        "CERRO SAN ANTONIO",
        "CONCORDIA",
        "EL PIÑON",
        "PEDRAZA",
        "PIVIJAY",
        "REMOLINO",
        "SALAMINA",
        "SITIONUEVO",
        "ZAPAYAN",
        "SANTA MARTA",
        "EL BANCO",
        "GUAMAL",
        "PIJIÑO DEL CARMEN",
        "SAN SEBASTIAN DE BUENAVISTA",
        "SAN ZENON",
        "SANTA ANA",
        "SANTA BARBARA DE PINTO",
      ],
    },
    {
      departamento: "META",
      municipios: [
        "EL CASTILLO",
        "EL DORADO",
        "FUENTE DE ORO",
        "GRANADA",
        "LA MACARENA",
        "LA URIBE",
        "LEJANÍAS",
        "MAPIRIPaN",
        "MESETAS",
        "PUERTO CONCORDIA",
        "PUERTO LLERAS",
        "PUERTO RICO",
        "SAN JUAN DE ARAMA",
        "VISTA HERMOSA",
        "VILLAVICENCIO",
        "ACACiAS",
        "BARRANCA DE UPIA",
        "CASTILLA LA NUEVA",
        "CUMARAL",
        "EL CALVARIO",
        "GUAMAL",
        "RESTREPO",
        "SAN CARLOS GUAROA",
        "SAN JUANITO",
        "SAN LUIS DE CUBARRAL",
        "SAN MARTÍN",
        "CABUYARO",
        "PUERTO GAITÁN",
        "PUERTO LoPEZ",
      ],
    },
    {
      departamento: "NARIÑO",
      municipios: [
        "CHACHAGUI",
        "CONSACA",
        "EL PEÑOL",
        "EL TAMBO",
        "LA FLORIDA",
        "NARIÑO",
        "PASTO",
        "SANDONÁ",
        "TANGUA",
        "YACUANQUER",
        "ANCUYA",
        "GUAITARILLA",
        "LA LLANADA",
        "LINARES",
        "LOS ANDES",
        "MALLAMA",
        "OSPINA",
        "PROVIDENCIA",
        "RICAURTE",
        "SAMANIEGO",
        "SANTA CRUZ",
        "SAPUYES",
        "TUQUERRES",
        "BARBACOAS",
        "EL CHARCO",
        "FRANCISCO PIZARRO",
        "LA TOLA",
        "Magui",
        "MOSQUERA",
        "OLAYA HERRERA",
        "ROBERTO PAYAN",
        "SANTA BaRBARA",
        "TUMACO",
        "ALBAN",
        "ARBOLEDA",
        "BELEN",
        "BUESACO",
        "COLON",
        "CUMBITARA",
        "EL ROSARIO",
        "El Tablon de Gomez",
        "LA CRUZ",
        "LA UNION",
        "LEIVA",
        "POLICARPA",
        "SAN BERNARDO",
        "SAN LORENZO",
        "SAN PABLO",
        "SAN PEDRO DE CARTAGO",
        "TAMINANGO",
        "ALDANA",
        "CONTADERO",
        "CÓRDOBA",
        "CUASPUD",
        "CUMBAL",
        "FUNES",
        "GUACHUCAL",
        "GUALMATAN",
        "ILES",
        "IMUES",
        "IPIALES",
        "POTOSÍ",
        "PUERRES",
        "PUPIALES",
      ],
    },
    {
      departamento: "NORTE DE SANTANDER",
      municipios: [
        "ARBOLEDAS",
        "CUCUTILLA",
        "GRAMALOTE",
        "LOURDES",
        "SALAZAR",
        "SANTIAGO",
        "VILLA CARO",
        "BUCARASICA",
        "EL TARRA",
        "SARDINATA",
        "TIBÚ",
        "ABREGO",
        "CACHIRÁ",
        "CONVENCIÓN",
        "EL CARMEN",
        "HACARÍ",
        "LA ESPERANZA",
        "LA PLAYA",
        "OCAÑA",
        "SAN CALIXTO",
        "TEORAMA",
        "CÚCUTA",
        "EL ZULIA",
        "LOS PATIOS",
        "PUERTO SANTANDER",
        "SAN CAYETANO",
        "VILLA DEL ROSARIO",
        "CÁCOTA",
        "CHITAGÁ",
        "MUTISCUA",
        "PAMPLONA",
        "PAMPLONITA",
        "SILOS",
        "BOCHALEMA",
        "CHINÁCOTA",
        "DURANIA",
        "HERRÁN",
        "LABATECA",
        "RAGONVALIA",
        "TOLEDO",
      ],
    },
    {
      departamento: "PUTUMAYO",
      municipios: [
        "COLÓN",
        "MOCOA",
        "ORITO",
        "PUERTO ASIS",
        "PUERTO CAICEDO",
        "PUERTO GUZMAN",
        "PUERTO LEGUIZAMO",
        "SAN FRANCISCO",
        "SAN MIGUEL",
        "SANTIAGO",
        "SIBUNDOY",
        "VALLE DEL GUAMUEZ",
        "VILLA GARZON",
      ],
    },
    {
      departamento: "QUINDIO",
      municipios: [
        "ARMENIA",
        "BUENAVISTA",
        "CALARCA",
        "CoRDOBA",
        "GeNOVA",
        "PIJAO",
        "FILANDIA",
        "SALENTO",
        "CIRCASIA",
        "LA TEBAIDA",
        "Montengro",
        "QUIMBAYA",
      ],
    },
    {
      departamento: "RISARALDA",
      municipios: [
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "MARSELLA",
        "PEREIRA",
        "SANTA ROSA DE CABAL",
        "APÍA",
        "BALBOA",
        "BELÉN DE UMBRÍA",
        "GUÁTICA",
        "LA CELIA",
        "QUINCHiA",
        "SANTUARIO",
        "MISTRATÓ",
        "PUEBLO RICO",
      ],
    },
    {
      departamento: "SANTANDER",
      municipios: [
        "CHIMA",
        "CONFINES",
        "CONTRATACIÓN",
        "EL GUACAMAYO",
        "GALÁN",
        "GAMBITA",
        "GUADALUPE",
        "GUAPOTÁ",
        "HATO",
        "OIBA",
        "PALMAR",
        "PALMAS DEL SOCORRO",
        "SANTA HELENA DEL OPÓN",
        "SIMACOTA",
        "SOCORRO",
        "SUAITA",
        "CAPITANEJO",
        "CARCASÍ",
        "CEPITÁ",
        "CERRITO",
        "CONCEPCIÓN",
        "ENCISO",
        "GUACA",
        "MACARAVITA",
        "MÁLAGA",
        "MOLAGAVITA",
        "SAN ANDRÉS",
        "SAN JOSÉ DE MIRANDA",
        "SAN MIGUEL",
        "ARATOCA",
        "BARICHARA",
        "CABRERA",
        "CHARALÁ",
        "COROMORO",
        "CURITÍ",
        "ENCINO",
        "JORDÁN",
        "MOGOTES",
        "OCAMONTE",
        "ONZAGA",
        "PÁRAMO",
        "PINCHOTE",
        "SAN GIL",
        "SAN JOAQUÍN",
        "VALLE DE SAN JOSÉ",
        "VILLANUEVA",
        "BARRANCABERMEJA",
        "BETULIA",
        "EL CARMEN DE CHUCURÍ",
        "PUERTO WILCHES",
        "SABANA DE TORRES",
        "SAN VICENTE DE CHUCURÍ",
        "ZAPATOCA",
        "BUCARAMANGA",
        "CALIFORNIA",
        "CHARTA",
        "EL PLAYÓN",
        "FLORIDABLANCA",
        "GIRÓN",
        "LEBRÍJA",
        "LOS SANTOS",
        "MATANZA",
        "PIEDECUESTA",
        "RIONEGRO",
        "SANTA BÁRBARA",
        "SURATA",
        "TONA",
        "VETAS",
        "AGUADA",
        "ALBANIA",
        "BARBOSA",
        "BOLÍVAR",
        "CHIPATÁ",
        "CIMITARRA",
        "EL PEÑÓN",
        "FLORIÁN",
        "GUAVATÁ",
        "GuEPSA",
        "JESÚS MARÍA",
        "LA BELLEZA",
        "LA PAZ",
        "LANDÁZURI",
        "PUENTE NACIONAL",
        "PUERTO PARRA",
        "SAN BENITO",
        "SUCRE",
        "VÉLEZ",
      ],
    },
    {
      departamento: "SUCRE",
      municipios: [
        "GUARANDA",
        "MAJAGUAL",
        "SUCRE",
        "CHALÁN",
        "COLOSO",
        "MORROA",
        "OVEJAS",
        "SINCELEJO",
        "COVEÑAS",
        "PALMITO",
        "SAN ONOFRE",
        "SANTIAGO DE TOLÚ",
        "TOLÚ VIEJO",
        "BUENAVISTA",
        "COROZAL",
        "EL ROBLE",
        "GALERAS",
        "LOS PALMITOS",
        "SAMPUÉS",
        "SAN JUAN BETULIA",
        "SAN PEDRO",
        "SINCÉ",
        "CAIMITO",
        "LA UNIÓN",
        "SAN BENITO ABAD",
        "SAN MARCOS",
      ],
    },
    {
      departamento: "TOLIMA",
      municipios: [
        "AMBALEMA",
        "ARMERO",
        "FALAN",
        "FRESNO",
        "HONDA",
        "MARIQUITA",
        "PALOCABILDO",
        "CARMEN DE APICALÁ",
        "CUNDAY",
        "ICONONZO",
        "MELGAR",
        "VILLARRICA",
        "ATACO",
        "CHAPARRAL",
        "COYAIMA",
        "NATAGAIMA",
        "ORTEGA",
        "PLANADAS",
        "RIOBLANCO",
        "RONCESVALLES",
        "SAN ANTONIO",
        "ALVARADO",
        "ANZOÁTEGUI",
        "CAJAMARCA",
        "COELLO",
        "ESPINAL",
        "FLANDES",
        "IBAGUe",
        "PIEDRAS",
        "ROVIRA",
        "SAN LUIS",
        "VALLE DE SAN JUAN",
        "ALPUJARRA",
        "DOLORES",
        "GUAMO",
        "PRADO",
        "PURIFICACIÓN",
        "SALDAÑA",
        "SUÁREZ",
        "CASABIANCA",
        "HERVEO",
        "LeRIDA",
        "LiBANO",
        "MURILLO",
        "SANTA ISABEL",
        "VENADILLO",
        "VILLAHERMOSA",
      ],
    },
    {
      departamento: "VALLE DEL CAUCA",
      municipios: [
        "ANDALUCÍA",
        "BUGA",
        "BUGALAGRANDE",
        "CALIMA",
        "EL CERRITO",
        "GINEBRA",
        "GUACARÍ",
        "RESTREPO",
        "RIOFRIO",
        "SAN PEDRO",
        "TRUJILLO",
        "TULUÁ",
        "YOTOCO",
        "ALCALa",
        "ANSERMANUEVO",
        "ARGELIA",
        "BOLÍVAR",
        "CARTAGO",
        "EL ÁGUILA",
        "EL CAIRO",
        "EL DOVIO",
        "LA UNIÓN",
        "LA VICTORIA",
        "OBANDO",
        "ROLDANILLO",
        "TORO",
        "ULLOA",
        "VERSALLES",
        "ZARZAL",
        "BUENAVENTURA",
        "CAICEDONIA",
        "SEVILLA",
        "CALI",
        "CANDELARIA",
        "DAGUA",
        "FLORIDA",
        "JAMUNDÍ",
        "LA CUMBRE",
        "PALMIRA",
        "PRADERA",
        "VIJES",
        "YUMBO",
      ],
    },
    {
      departamento: "VAUPES",
      municipios: [
        "CARURU",
        "MITÚ",
        "PACOA",
        "PAPUNAHUA",
        "TARAIRA",
        "YAVARATÉ",
      ],
    },
    {
      departamento: "VICHADA",
      municipios: [
        "CUMARIBO",
        "LA PRIMAVERA",
        "PUERTO CARREÑO",
        "SANTA ROSALÍA",
      ],
    },
    {
      departamento: "",
      municipios: [],
    },
  ];

  const economicas = [
    "Cultivos agrícolas transitorios",
    "Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas",
    "Cultivo de arroz",
    "Cultivo de hortalizas, raíces y tubérculos",
    "Cultivo de tabaco",
    "Cultivo de plantas textiles",
    "Otros cultivos transitorios n.c.p",
    "Cultivos agrícolas permanentes",
    "Cultivo de frutas tropicales y subtropicales",
    "Cultivo de plátano y banano",
    "Cultivo de café",
    "Cultivo de caña de azúcar",
    "Cultivo de flor de corte",
    "Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos",
    "Cultivo de plantas con las que se preparan bebidas",
    "Cultivo de especias y de plantas aromáticas y medicinales",
    "Otros cultivos permanentes n.c.p.",
    "Propagación de plantas (actividades de los viveros, excepto viveros forestales)",
    "Propagación de plantas (actividades de los viveros, excepto viveros forestales).",
    "Ganadería.",
    "Cría de ganado bovino y bufalino.",
    "Cría de caballos y otros equinos.",
    "Cría de ovejas y cabras.",
    "Cría de ganado porcino.",
    "Cría de aves de corral.",
    "Cría de otros animales n.c.p.",
    "Explotación mixta (agrícola y pecuaria).",
    "Explotación mixta (agrícola y pecuaria).",
    "Actividades de apoyo a la agricultura y la ganadería, y actividades posteriores a la cosecha.",
    "Actividades de apoyo a la agricultura.",
    "Actividades de apoyo a la ganadería.",
    "Actividades posteriores a la cosecha.",
    "Tratamiento de semillas para propagación.",
    "Caza ordinaria y mediante trampas y actividades de servicios conexas.",
    "Caza ordinaria y mediante trampas y actividades de servicios conexas.",
    "Silvicultura y otras actividades forestales.",
    "Silvicultura y otras actividades forestales.",
    "Extracción de madera.",
    "Extracción de madera.",
    "Recolección de productos forestales diferentes a la madera.",
    "Recolección de productos forestales diferentes a la madera.",
    "Servicios de apoyo a la silvicultura.",
    "Servicios de apoyo a la silvicultura.",
    "Pesca.",
    "Pesca marítima.",
    "Pesca de agua dulce.",
    "Acuicultura.",
    "Acuicultura marítima.",
    "Acuicultura de agua dulce.",
    "Extracción de hulla (carbón de piedra).",
    "Extracción de hulla (carbón de piedra).",
    "Extracción de carbón lignito.",
    "Extracción de carbón lignito.",
    "Extracción de petróleo crudo.",
    "Extracción de petróleo crudo.",
    "Extracción de gas natural.",
    "Extracción de gas natural.",
    "Extracción de minerales de hierro.",
    "Extracción de minerales de hierro.",
    "Extracción de minerales metalíferos no ferrosos.",
    "Extracción de minerales de uranio y de torio.",
    "Extracción de oro y otros metales preciosos.",
    "Extracción de minerales de níquel.",
    "Extracción de otros minerales metalíferos no ferrosos n.c.p.",
    "Extracción de piedra, arena, arcillas, cal, yeso, caolín, bentonitas y similares",
    "Extracción de piedra, arena, arcillas comunes, yeso y anhidrita.",
    "Extracción de arcillas de uso industrial, caliza, caolín y bentonitas.",
    "Extracción de esmeraldas, piedras preciosas y semipreciosas.",
    "Extracción de esmeraldas, piedras preciosas y semipreciosas.",
    "Extracción de otros minerales no metálicos n.c.p.",
    "Extracción de minerales para la fabricación de abonos y productos químicos.",
    "Extracción de halita (sal).",
    "Extracción de otros minerales no metálicos n.c.p.",
    "Actividades de apoyo para la extracción de petróleo y de gas natural.",
    "Actividades de apoyo para la extracción de petróleo y de gas natural.",
    "Actividades de apoyo para otras actividades de explotación de minas y canteras",
    "Procesamiento y conservación de carne, pescado, crustáceos y moluscos.",
    "Procesamiento y conservación de carne y productos cárnicos.",
    "Procesamiento y conservación de pescados, crustáceos y moluscos.",
    "Procesamiento y conservación de frutas, legumbres, hortalizas y turbérculo",
    "Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos.",
    "Elaboración de aceites y grasas de origen vegetal y animal.",
    "Elaboración de aceites y grasas de origen vegetal y animal.",
    "Elaboración de productos lácteos.",
    "Elaboración de productos lácteos.",
    "Elaboración de productos de molinería, almidones y productos derivados del almidón.",
    "Elaboración de productos de molinería.",
    "Elaboración de almidones y productos derivados del almidón.",
    "Elaboración de productos de café.",
    "Trilla de café.",
    "Descafeinado, tostión y molienda del café.",
    "Otros derivados del café.",
    "Elaboración de azúcar y panela.",
    "Elaboración y refinación de azúcar.",
    "Elaboración de panela.",
    "Elaboración de otros productos alimenticios.",
    "Elaboración de productos de panadería.",
    "Elaboración de cacao, chocolate y productos de confitería.",
    "Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares.",
    "Elaboración de comidas y platos preparados.",
    "Elaboración de otros productos alimenticios n.c.p.",
    "Elaboración de alimentos preparados para animales.",
    "Elaboración de alimentos preparados para animales.",
    "Elaboración de bebidas.",
    "Destilación, rectificación y mezcla de bebidas alcohólicas.",
    "Elaboración de bebidas fermentadas no destiladas.",
    "Producción de malta, elaboración de cervezas y otras bebidas malteadas.",
    "Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas.",
    "Elaboración de productos de tabaco.",
    "Elaboración de productos de tabaco.",
    "Preparación, hilatura, tejeduría y acabado de productos textiles.",
    "Preparación e hilatura de fibras textiles.",
    "Tejeduría de productos textiles.",
    "",
  ];

  const { enqueueSnackbar } = useSnackbar();
  const router = useRouter();
  const [form, setForm] = useState({
    nombre: "",
    nit: "",
    alias: "",
    actividad_economica: "",
    direccion: "",
    municipio_dane: "",
    telefono: "",
    correo: "",
  });
  const crearEmpresa = async (values: any) => {
    let response;
    try {
      response = await crearEmpresasRequest(values);
      console.log(response);
      response.data.statusCode == "200"
        ? enqueueSnackbar(`${response.data.message}`, { variant: "warning" })
        : enqueueSnackbar(`${response.data.message}`, { variant: "success" });
      router.push("/empresas")
    } catch (e) {
      if (e == "Error: Request failed with status code 400") {
        enqueueSnackbar("Problemas creando la empresa, vuelva a intentar", {
          variant: "warning",
        });
      }
    }
  };
  const handleChange = (e: any) => {
    const { name, value } = e.target;
    setForm((prevFormData) => ({
      ...prevFormData,
      [name]: value,
    }));
  };
  const handleSubmit = (e: any) => {
    e.preventDefault();
    console.log(form);
    crearEmpresa(form);
  };
  return (
    <Container
      maxWidth="xl"
      component={motion.div}
      initial={{ x: "30%" }}
      animate={{ x: "0%" }}
      style={{ marginTop: "30px" }}
    >
      <Paper
        elevation={4}
        style={{ padding: "30px 20px", borderRadius: "12px" }}
      >
        <form onSubmit={handleSubmit}>
          <Grid container spacing={3}>
            <Grid item xs={11.5} sm={12} lg={12} sx={{ marginLeft: "20px" }}>
              <Typography variant="h6" gutterBottom>
                nombre de la empresa
              </Typography>
            </Grid>

            <Grid item xs={11} sm={11} lg={5.5}>
              <FormControl fullWidth>
                <TextField
                  multiline
                  placeholder="nombre"
                  name="nombre"
                  value={form.nombre}
                  onChange={handleChange}
                />
              </FormControl>
            </Grid>

            <Grid item xs={11} sm={11} lg={5.5}>
              <FormControl fullWidth>
                <TextField
                  multiline
                  placeholder="nit"
                  name="nit"
                  value={form.nit}
                  onChange={handleChange}
                />
              </FormControl>
            </Grid>

            <Grid item xs={11} sm={11} lg={5.5}>
              <FormControl fullWidth>
                <TextField
                  multiline
                  placeholder="alias"
                  name="alias"
                  value={form.alias}
                  onChange={handleChange}
                />
              </FormControl>
            </Grid>

            <Grid item xs={11} sm={11} lg={5.5}>
              <FormControl fullWidth>
                <TextField
                  multiline
                  placeholder="actividad_economica"
                  name="actividad_economica"
                  value={form.actividad_economica}
                  onChange={handleChange}
                />
              </FormControl>
            </Grid>

            <Grid item xs={11} sm={11} lg={5.5}>
              <FormControl fullWidth>
                <TextField
                  multiline
                  placeholder="direccion"
                  name="direccion"
                  value={form.direccion}
                  onChange={handleChange}
                />
              </FormControl>
            </Grid>

            <Grid item xs={11} sm={11} lg={5.5}>
              <FormControl fullWidth>
                <TextField
                  multiline
                  placeholder="municipio_dane"
                  label="municipio_dane"
                  name="municipio_dane"
                  value={form.municipio_dane}
                  onChange={handleChange}
                  select
                >
                  {colombia.map((departamento, index) => (
                    <MenuItem value={departamento.departamento} key={index}>
                      {departamento.departamento}
                    </MenuItem>
                  ))}
                </TextField>
              </FormControl>
            </Grid>

            <Grid item xs={11} sm={11} lg={5.5}>
              <FormControl fullWidth>
                <TextField
                  multiline
                  placeholder="telefono"
                  name="telefono"
                  value={form.telefono}
                  onChange={handleChange}
                />
              </FormControl>
            </Grid>

            <Grid item xs={11} sm={11} lg={5.5}>
              <FormControl fullWidth>
                <TextField
                  multiline
                  placeholder="correo"
                  name="correo"
                  value={form.correo}
                  onChange={handleChange}
                />
              </FormControl>
            </Grid>

            <Grid item xs={11} sm={11}>
              <Stack spacing={2} direction="row">
                <Button fullWidth type="submit" variant="contained">
                  Guardar
                </Button>
              </Stack>
            </Grid>
          </Grid>
        </form>
      </Paper>
    </Container>
  );
};
export default Crear;
